namespace Ecommerce.Domain.Attributes
{
    public class AttributesBodyEmail
    {
        protected string SubjectConfirmation { get; private set; } = "Confirmação de compra - Transação n° ";
        protected string ConfirmationEmail { get; private set; } = "@\"\r\n<html>\r\n    <body style='font-family: Arial, sans-serif; line-height: 1.6;'>\r\n        <h2 style='color: #2c3e50;'>Compra confirmada com sucesso!</h2>\r\n        \r\n        <p>Olá <strong>{TransactionData.UserName}</strong>,</p>\r\n\r\n        <p>\r\n            Obrigado por sua compra! Seu pedido \r\n            <strong>nº {TransactionData.TransactionId}-{DateTime.Now:yyyyMMdd}</strong> \r\n            foi confirmado com sucesso no dia \r\n            <strong>{TransactionData.TransactionDate:dd/MM/yyyy}</strong> às \r\n            <strong>{TransactionData.TransactionDate:HH:mm}</strong>.\r\n        </p>\r\n\r\n        <h3>Detalhes do Pedido:</h3>\r\n        <ul>\r\n            {string.Join(\"\", TransactionData.ShoppingList.Select(item => $\"<li>{item.Item1} - Quantidade: {item.Item2}</li>\"))}\r\n            <li><strong>Valor Total:</strong> R$ {TransactionData.TotalValue:F2}</li>\r\n            <li><strong>Forma de Pagamento:</strong> ...</li>\r\n        </ul>\r\n\r\n        <p>Você receberá uma nova notificação assim que o pedido for enviado.</p>\r\n\r\n        <p>\r\n            Atenciosamente,<br>\r\n            <strong>Equipe X</strong>\r\n        </p>\r\n\r\n        <hr>\r\n        <small style='color: gray;'>Este é um e-mail automático. Por favor, não responda.</small>\r\n    </body>\r\n</html>\r\n\"\r\n";
       
        protected string SubjectShippingConfirmation { get; private set; } = "Compra cancelada - Transação n° ";
        protected string CancellationEmail { get; private set; } = "$@\"\r\n<html>\r\n    <body style='font-family: Arial, sans-serif;'>\r\n        <h2 style='color: #e74c3c;'>Compra cancelada</h2>\r\n        <p>Olá <strong>{TransactionData.UserName}</strong>,</p>\r\n        <p>Informamos que o seu pedido <strong>nº {TransactionData.TransactionId}</strong> foi <strong>cancelado</strong> em {TransactionData.TransactionDate.ToString(\"dd/MM/yyyy\")} às {TransactionData.TransactionDate:HH:mm}.</p>\r\n\r\n        <h3>Resumo do Pedido:</h3>\r\n        <ul>\r\n            <li>Produtos: {string.Join(\", \", TransactionData.ShoppingList.Select(p => $\"{p.Item1} (Qtd: {p.Item2})\"))}</li>\r\n            <li>Valor Estimado: R$ {TransactionData.TotalValue}</li>\r\n            <li>Status: Cancelado</li>\r\n        </ul>\r\n\r\n        <p>Caso isso tenha ocorrido por engano, entre em contato conosco para mais informações.</p>\r\n\r\n        <p>Atenciosamente,<br><strong>Equipe Projeto E-Commerce .NET</strong></p>\r\n\r\n        <hr>\r\n        <small style='color: gray;'>Este é um e-mail automático. Por favor, não responda.</small>\r\n    </body>\r\n</html>\r\n\"\r\n";

        protected string SubjectShippingCanceled { get; private set; } = "Confirmação de envio - Transação n° ";
        protected string ShippingConfirmationEmail { get; private set; } = "@\"\r\n<html>\r\n    <body style='font-family: Arial, sans-serif;'>\r\n        <h2 style='color: #27ae60;'>Seu pedido foi enviado! 🚚</h2>\r\n        <p>Olá <strong>{TransactionData.UserName}</strong>,</p>\r\n        <p>Boas notícias! O seu pedido <strong>nº {TransactionData.TransactionId}</strong> foi enviado em {DateTime.Now:dd/MM/yyyy}.</p>\r\n\r\n        <h3>Detalhes do Pedido:</h3>\r\n        <ul>\r\n            <li>Produtos: {string.Join(\", \", TransactionData.ShoppingList.Select(p => $\"{p.Item1} (Qtd: {p.Item2})\"))}</li>\r\n            <li>Valor Total: R$ {TransactionData.TotalValue}</li>\r\n            <li>Forma de Pagamento: ...</li>\r\n        </ul>\r\n\r\n        <p>O código de rastreio será enviado em breve (se aplicável). Fique atento à sua caixa de entrada e à entrega!</p>\r\n\r\n        <p>Atenciosamente,<br><strong>Equipe X</strong></p>\r\n\r\n        <hr>\r\n        <small style='color: gray;'>Este é um e-mail automático. Por favor, não responda.</small>\r\n    </body>\r\n</html>\r\n\"";
    }
}
